// Example template data with images, categories, and descriptions
export const allTemplates = [
    {
        id: 1,
        name: "Portfolio",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "Showcase your work with a beautiful portfolio.",
    },
    {
        id: 2,
        name: "E-Commerce",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "Sell your products online with ease.",
    },
    {
        id: 3,
        name: "Blog",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "Start your blog and share your stories.",
    },
    {
        id: 4,
        name: "Agency",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "A template designed for agencies.",
    },
    {
        id: 5,
        name: "Startup",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "Perfect for new startups.",
    },
    {
        id: 6,
        name: "Landing Page",
        category: "Marketing",
        image: "https://via.placeholder.com/300",
        description: "Convert leads with a high-quality landing page.",
    },
    {
        id: 7,
        name: "Photography",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "Display your photography portfolio.",
    },
    {
        id: 8,
        name: "Resume",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "A sleek resume template.",
    },
    {
        id: 9,
        name: "Consulting",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "Promote your consulting services.",
    },
    {
        id: 10,
        name: "Event",
        category: "Marketing",
        image: "https://via.placeholder.com/300",
        description: "Promote your events with this template.",
    },
    {
        id: 11,
        name: "Creative Agency",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "A stunning template for creative agencies.",
    },
    {
        id: 12,
        name: "Fitness",
        category: "Health",
        image: "https://via.placeholder.com/300",
        description: "A template for fitness coaches and gyms.",
    },
    {
        id: 13,
        name: "Restaurant",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "A beautiful template for restaurants and cafes.",
    },
    {
        id: 14,
        name: "Wedding",
        category: "Event",
        image: "https://via.placeholder.com/300",
        description: "Capture the magic of weddings.",
    },
    {
        id: 15,
        name: "Artist Portfolio",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "Showcase your art with this template.",
    },
    {
        id: 16,
        name: "Corporate",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "A professional corporate website template.",
    },
    {
        id: 17,
        name: "Technology",
        category: "Tech",
        image: "https://via.placeholder.com/300",
        description: "A tech-focused website template.",
    },
    {
        id: 18,
        name: "Online Course",
        category: "Education",
        image: "https://via.placeholder.com/300",
        description: "A template for online course creators.",
    },
    {
        id: 19,
        name: "Non-Profit",
        category: "Charity",
        image: "https://via.placeholder.com/300",
        description: "Raise awareness for your cause.",
    },
    {
        id: 20,
        name: "Real Estate",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "A template for real estate businesses.",
    },
    {
        id: 21,
        name: "Church",
        category: "Charity",
        image: "https://via.placeholder.com/300",
        description: "A template for church and religious organizations.",
    },
    {
        id: 22,
        name: "Podcast",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "Share your podcasts with this modern template.",
    },
    {
        id: 23,
        name: "App Landing",
        category: "Tech",
        image: "https://via.placeholder.com/300",
        description: "Showcase your app with an impressive landing page.",
    },
    {
        id: 24,
        name: "Education",
        category: "Education",
        image: "https://via.placeholder.com/300",
        description:
            "A template for schools, colleges, and educational institutions.",
    },
    {
        id: 25,
        name: "Healthcare",
        category: "Health",
        image: "https://via.placeholder.com/300",
        description: "A professional template for healthcare providers.",
    },
    {
        id: 26,
        name: "Music Band",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "Promote your music band with this vibrant template.",
    },
    {
        id: 27,
        name: "Law Firm",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "A template designed for law firms and legal services.",
    },
    {
        id: 28,
        name: "Portfolio Dark",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "A dark-themed portfolio template for professionals.",
    },
    {
        id: 29,
        name: "Travel Agency",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "A stunning template for travel agencies.",
    },
    {
        id: 30,
        name: "Architecture",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "A template for architecture firms and professionals.",
    },
    {
        id: 31,
        name: "Fashion Store",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "Sell your fashion products with this stylish template.",
    },
    {
        id: 32,
        name: "Photography Dark",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "A dark-themed photography portfolio.",
    },
    {
        id: 33,
        name: "Fitness Club",
        category: "Health",
        image: "https://via.placeholder.com/300",
        description: "Promote your fitness club with this powerful template.",
    },
    {
        id: 34,
        name: "Charity Event",
        category: "Charity",
        image: "https://via.placeholder.com/300",
        description: "Raise funds and awareness with this event template.",
    },
    {
        id: 35,
        name: "Personal Blog",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "A modern blog template for sharing personal stories.",
    },
    {
        id: 36,
        name: "Interior Design",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "A template for interior designers and decorators.",
    },
    {
        id: 37,
        name: "Crypto",
        category: "Tech",
        image: "https://via.placeholder.com/300",
        description: "A futuristic template for cryptocurrency projects.",
    },
    {
        id: 38,
        name: "Pet Care",
        category: "Health",
        image: "https://via.placeholder.com/300",
        description: "A template for pet care services and products.",
    },
    {
        id: 39,
        name: "Cooking Blog",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description:
            "Share your favorite recipes with this cooking blog template.",
    },
    {
        id: 40,
        name: "Environmental",
        category: "Charity",
        image: "https://via.placeholder.com/300",
        description: "Promote environmental causes with this green template.",
    },
    {
        id: 41,
        name: "Game Store",
        category: "Tech",
        image: "https://via.placeholder.com/300",
        description: "Sell your games and accessories with this template.",
    },
    {
        id: 42,
        name: "Portfolio Minimal",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "A minimalistic portfolio template for creatives.",
    },
    {
        id: 43,
        name: "Music Festival",
        category: "Event",
        image: "https://via.placeholder.com/300",
        description: "Promote your music festival with this energetic template.",
    },
    {
        id: 44,
        name: "Freelancer",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description: "A template for freelancers to showcase their services.",
    },
    {
        id: 45,
        name: "Online Store",
        category: "Business",
        image: "https://via.placeholder.com/300",
        description: "Start your online store with this modern template.",
    },
    {
        id: 46,
        name: "Charity Organization",
        category: "Charity",
        image: "https://via.placeholder.com/300",
        description:
            "Support your charity organization with this impactful template.",
    },
    {
        id: 47,
        name: "Magazine",
        category: "Creative",
        image: "https://via.placeholder.com/300",
        description: "A template for online magazines and publications.",
    },
    {
        id: 48,
        name: "Portfolio Pro",
        category: "Personal",
        image: "https://via.placeholder.com/300",
        description:
            "A professional portfolio template for showcasing your work.",
    },
    {
        id: 49,
        name: "Event Planner",
        category: "Event",
        image: "https://via.placeholder.com/300",
        description: "Plan and promote events with this versatile template.",
    },
    {
        id: 50,
        name: "Online Learning",
        category: "Education",
        image: "https://via.placeholder.com/300",
        description: "A template for online learning platforms and educators.",
    },
];

